name: uran_company_test_task
description: A test task for UranCompany from Yevhen Tymchenko

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  json_annotation: ^4.5.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: any
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^2.0.3
  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/